title: "The Future of Money and HCI"
description: "CHI 2025 Workshop | Yokohama, Japan"
baseurl: /
url: https://hci.money

permalink: pretty
remote-theme: "piazzai/jekyll-nagymaros"

home: /
copyright: 
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

whitelist: [jekyll-analytics]
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics

sass:
  sourcemap: never

jekyll_analytics:
  GoogleAnalytics: G-X8HGV5RMNG
