title: "The Future of Money and HCI"
description: "CHI 2025 Workshop | Yokohama, Japan"
baseurl: /
url: https://hci.money

permalink: pretty
theme: jekyll-nagymaros

home: /
copyright: 
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  

